### ISSUE TITLE
Is there any Update for Foundation ?

### ISSUE THREAD

**Issue by jamon8888** [axyz/zurb-foundation.docpad#1]
I cannot do it ( not enought skills ) but it will be a good addition since 4 is really powerfull and taking on Bootstrap

**Comment by axyz** [comment]
you are right, i'll try to do it as soon as possible

**Comment by axyz** [comment]
sorry for the long wait... I'm now building a foundation 4.3.2 branch and i'll merge it onto master as soon i'll resolve a little JS problem: it just do not see foundation() function, maybe is some kind of conflict with zepto or, who knows, some silly typo. I've done it more lightweight using nodesass, coffescript(quite optional) and eco (I prefer handlebars politics in separation between logic and content... but for now i'll use eco, then later i'll evaluate if it's a good idea to switch to hb.

next plans: a good min and lint and maybe a basic usage of collection (automatic menu with pages and blog post but i'd like to keep it as simple and not specific as possible)
