### ISSUE TITLE
Real update to Foundation 4

### ISSUE THREAD

**Issue by seniorpreacher** [axyz/zurb-foundation.docpad#3]
I really thank you for creating this repo, it helped me, but there are lot of thing, that is still connected to Foundation 3.

I'm just started to use Foundation, so I don't know everything about this, but I had to make changes to get my project run.
- at _setting.scss:
  remove 'ratios' import (doesn't exist anymore.
  rename every variable from camelCase to use scores (ex. row-width)
- at the demo index.html, the column class names was written with the old style (ex. six) not the new (small-6)

Probably there are more differences.

Cheers!

**Comment by axyz** [comment]
sorry for the long wait... I'm now building a foundation 4.3.2 branch and i'll merge it onto master as soon i'll resolve a little JS problem: it just do not see foundation() function, maybe is some kind of conflict with zepto or, who knows, some silly typo. I've done it more lightweight using nodesass, coffescript(quite optional) and eco (I prefer handlebars politics in separation between logic and content... but for now i'll use eco, then later i'll evaluate if it's a good idea to switch to hb.

next plans: a good min and lint and maybe a basic usage of collection (automatic menu with pages and blog post but i'd like to keep it as simple and not specific as possible)
