### ISSUE TITLE
Foundation 5

### ISSUE THREAD

**Issue by refactornator** [axyz/zurb-foundation.docpad#5]
[Foundation 5 was recently released](http://foundation.zurb.com/), would be good to upgrade this skeleton to use it.

**Comment by axyz** [comment]
I'm planning to do it as soon as possible (2 or 3 days) thanks for the advice.

**Comment by axyz** [comment]
super quick release just for you :P let me know if you find some bugs. Note that now you have to perform a bower install after the initial npm install, because now foundation uses bower to update.

**Comment by k-j-kleist** [comment]
Awesome - it actually works! Contrary to the standard installation, selecting skeleton 16 "Zurb Foundation(SASS)" which aborts after the skeleton installation due to an error.
