### ISSUE TITLE
Long pause on page generation

### ISSUE THREAD

**Issue by simonh1000** [axyz/zurb-foundation.docpad#7]
I'm not sure where the issue lies, but compared to the regeneration speeds I saw on talks given by Ben, the regeneration speed with my foundation based setup using this code is very slow. There is a 5 second pause midway through the generation where it says:

Performing generate: Fetch data to render at 2/9 22%

Feels like it is downloading something but I can't prove that.
Any ideas?

**Comment by axyz** [comment]
Hi there,
I'll make a test as soon as i have a little time. By the way are you referring to a clean installation or have you added some content and in that case what have you added? And also are you talking about livereload or issuing the build command?
